# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc9677b135ab1689462844b9b9b3549f19eb892b60e854d4d6ab908bafcb6d25ab90a5f01f1f30a5303cf48cb5aa49df532533010fe39814784330636b3a29a3

test:
  secret_key_base: 81772be4b68d4f7c786681475a898c25d7c310bce5af7f0c35d4b4639bc2709a80712b2ff0e81445d761aa58454b33934b0f94c4dd7c272f074017d27bd62548

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
