# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 087ff27ac33c884d8f6fd1cee42e098308affb9ebf706db7e543e062b549e85c0f3270a8046407e24ecfc7616827cc09a742e114a477ccf3a37d5d70f8cf642b

test:
  secret_key_base: d8c762d04027bd15fd20f714bd02acf7ef9270a4e5d3eddbd51c13264b4c5b7d74dffed484a84ee1859b60c12beede20d58bee0d959eb7c8e7e03ecedce1a475

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
