# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6741d34ee2f879218cb63e5f789490d74ea8756ea31e4f6c69abd864dc51a8b23949b51a1760a007c239d43ba2b98d13acab9ae4673782718d6417f39817eec6

test:
  secret_key_base: d58082aac1a3377784c4db079f4b74de2cf3cf74498a5a2f998fc3d39cf05f61bb4b02b9e7983e3cce723bdf11de8004b3ba7cbf1af7ce74e8ee5adfc7d59734

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
