# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fdc1e6dd0976678a367a9f564b848c1d5f9bc0a338ac2e83997ddea1ca9750716717fb0f17bd104b84284f7f73e8ca81fdd1a3308151b002702fe8d65a0c22aa

test:
  secret_key_base: 7057a653bfac82bafd8df2d15f4dfdd6cc439e1bf262151d242e4ae33d3ee332e8257b38684e2dd3909e7f4811ac87ce21d6af4e124e07f1c02803378c6aa772

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
