# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04bb5f2ba18454d78e69ba80e7e76ff9e4bc26958901fcd25977bed2c320dab9f6f770e634435a78b135f67cda2b2a9a10775270f5de2cb1e1a29b9e52f5889a

test:
  secret_key_base: a95a3e9568e28143cbbdff04920fd0c119596132f0a7fb023e8c45ebdab88ae837f81de38e0c4bf93eab4b407c92de08197c78a7a5a918a0c254f7d831944011

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
