# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cb01d9e21f648b4c5dca7305c14eb37c67c59136e729ae6df9bf2c82c6a8f078b0b1908b8915871df1e557bd2115e2a24cdd6e8df2e0637479018940755c689

test:
  secret_key_base: 1b44e32f04b596275c4d7b05a1fb4bab5822633246b3645764bc35c7c36f487587ddd5082515e75763864581437bed8cfa96beeab30e7de922a9764c2124fce6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
